import os
import platform
import torch
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("/mnt/maldect_ssd_2T/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("/mnt/maldect_ssd_2T/chatglm3-6b", trust_remote_code=True, device='cuda')
model = model.eval()
response, history = model.chat(tokenizer, "Screen:\n<div class=\"cancel\">  </div>\n<div class=\"save\">  </div>\n<div class=\"picture\">  </div>\n<p class=\"tag_label\"> List </p>\n<input class=\"tag_name\" placeholder=\"Enter list name\">  </input>\n<p> Shared With </p>\n<div class=\"icon\">  </div>\n<div class=\"text1\" placeholder=\"Contact or Email\"> actfm_last_nameactfm_first_nameactfm_picturebeast_mode_orderbackupErroractive_tasks_ordergcm_needs_regactfm_namegtasks_usertoday_tasks_orderwidget-values-widget-title-custom_files_diractfm_emailwidget-extras-last_incoming_numberactfm_userwidget-sql-gtasks_defaultlistwidget-intent- </div>\n<div class=\"button1\">  </div>\n<div class=\"divider\">  </div>\n<div class=\"icon\">  </div>\n<div class=\"text1\" placeholder=\"Contact or Email\"> actfm_last_nameactfm_first_nameactfm_picturebeast_mode_orderbackupErroractive_tasks_ordergcm_needs_regactfm_namegtasks_usertoday_tasks_orderwidget-values-widget-title-custom_files_diractfm_emailwidget-extras-last_incoming_numberactfm_userwidget-sql-gtasks_defaultlistwidget-intent- </div>\n<div class=\"button1\">  </div>\n<div class=\"divider\">  </div>\n<p> Share with anyone who has an email address </p>\n<p class=\"description_label\"> Description </p>\n<input class=\"tag_description\" placeholder=\"Type a description here\">  </input>\n<p class=\"settings_label\"> Settings </p>\n<p> Silence Notifications </p>\n<div class=\"tag_silenced\">  </div>\n<div class=\"divider\">  </div>\n<p> Create Desktop Shortcut </p>\n<div class=\"create_shortcut\">  </div>\n<button class=\"leave_list\"> Leave this list </button>\nNow reasoning starts:\nWhat is the purpose of the screen?", history=[{'role':'user' ,'content':'Screen:\n<p id=0 class="alertTitle"> Create password </p>\n<div id=1 class="titleDivider"> </div>\n<input id=2 class="password"> Crowd3116 </input>\n<input id=3 class="confirm password"> Crowd3116 </input>\n<input id=4 class="hint"> c3 </input>\n<input id=5 class="edEmailAddress"> appcrawler4@gmail.com </input>\n<p id=6 class="tvEmailAddressInfo"> This email address will be used to reset your password. </p>\n<button id=7 class="button2"> Cancel </button>\n<button id=8 class="button1"> 0K </button>\nNow reasoning starts:\nHow many input tags are there on the screen?'},{'role': 'assistant', 'metadata': '', 'content': '4'},{'role': 'user', 'content': 'What is the purpose of the screen?'},{'role': 'assistant', 'metadata': '', 'content': 'The screen is used to create a password'}])
print(response)
print(history)